apiVersion: apps/v1
kind: Deployment
metadata:
  name: gol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gol
  template:
    metadata:
      labels:
        app: gol
    spec:
      containers:
      - name: gol
        image: dockerranganath/demo_repo:0221
        ports:
        - containerPort: 80
